// This folder contains utils that are only required by the background
export * from "./onTabChange";
export * from "./removeBadge";
export * from "./showExtensionIcon";
export * from "./getSpecialIconPath";
export * from "./showBadge";
export * from "./showCountryFlagIcon";
export * from "./getExtensionIconPath";
export * from "./showOnionAddressIcon";
export * from "./getPreferredColorScheme";
export * from "./handleTab";
export * from "./showIcon";
export * from "./isSearchBarIconShown";
export * from "./setToolbarIconVisibility";
export * from "./handleStorageChange";
export * from "./handleActiveTabs";

export { default as onTabChange } from "./onTabChange";
export { default as removeBadge } from "./removeBadge";
export { default as showExtensionIcon } from "./showExtensionIcon";
export { default as getSpecialIconPath } from "./getSpecialIconPath";
export { default as showBadge } from "./showBadge";
export { default as showCountryFlagIcon } from "./showCountryFlagIcon";
export { default as getExtensionIconPath } from "./getExtensionIconPath";
export { default as showOnionAddressIcon } from "./showOnionAddressIcon";
export { default as getPreferredColorScheme } from "./getPreferredColorScheme";
export { default as handleTab } from "./handleTab";
export { default as showIcon } from "./showIcon";
export { default as isSearchBarIconShown } from "./isSearchBarIconShown";
export { default as setToolbarIconVisibility } from "./setToolbarIconVisibility";
export { default as handleStorageChange } from "./handleStorageChange";
export { default as handleActiveTabs } from "./handleActiveTabs";
