name: Publish extension

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  chrome:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Install global requirements
        run: yarn global add zx svgexport

      - name: Install requirements
        run: yarn

      - name: Preprocess
        run: yarn run preprocess --browser=chrome

      - name: Get name
        id: name
        run: echo "::set-output name=name::$(./getFilename.mjs --browser=chrome)"

      - name: Build extension
        run: yarn run build:extension

      - name: Zip Extension with web-ext
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: dist
          filename: ${{ steps.name.outputs.name }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-build.outputs.target }}

  firefox:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Install global requirements
        run: yarn global add zx svgexport

      - name: Install requirements
        run: yarn

      - name: Preprocess
        run: yarn run preprocess --browser=firefox

      - name: Get name
        id: name
        run: echo "::set-output name=name::$(./getFilename.mjs --browser=firefox)"

      - name: Build extension
        run: yarn run build:extension

      - name: Zip Extension with web-ext
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: dist
          filename: ${{ steps.name.outputs.name }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-build.outputs.target }}

      - name: Sign in & publish
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          channel: listed
          source: ${{ steps.web-ext-build.outputs.target }}
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_CLIENT_SECRET }}
