name: Test Workflow

on:
  - push

jobs:
  healt-check-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install

      - name: Chrome - Run linter 👀
        run: yarn run lint --browser=chrome
      - name: Chrome - Run tests 🧪
        run: yarn run test --browser=chrome
      - name: Chrome - Test build 🚀
        run: yarn run build:extension --browser=chrome

      - name: Firefox - Run linter 👀
        run: yarn run lint --browser=firefox
      - name: Firefox - Run tests 🧪
        run: yarn run test --browser=firefox
      - name: Firefox - Test build 🚀
        run: yarn run build:extension --browser=firefox
